### PR TITLE
reproducibility tutorial in-class example of using good coding

### PR DESCRIPTION
**Pull request by grahamas**
Sufficient example.

Could be extended to be example about 1) extensibility (changing incomes, rates); 2) extensibility with other functions (changable taxation); 3) probability and seeds (interest rates drawn from probability distribution).

### CODE REVIEW

**Comment by grahamas** [comment]
@sepalmer: could you review?

**Comment by sepalmer** [comment]
I'd like to see this in the Rmd, so that the workbook functions as its own "thing"

**Comment by sepalmer** [comment]
I like the example!

**Review by sepalmer — APPROVED** [review]
This looks good! I will make a small change: I will put the CuteNameHere.R file in the "code" folder for the class so that they can open and view it without cloning a repo in this stage.

**Comment by sepalmer** [comment]
Stefano, we have a conflicting PDF file that we can just re-knit after we merge this branch, but I can't do that from my phone. Can you add Graham as a collaborator or do the command line magic to merge this commit?

**Pull request merged**
